name: Build API Image

on:
  push:
    branches: [ master, relase ]
  pull_request:
    branches: [ master, relase ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file ./src/Dotnet5.GraphQL3.Store.WebAPI/Dockerfile --tag my-image-name:$(date +%s)
